name: publish 
on:
  push:
    branches: 
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    name: Download and publish JSON schemas
    if: github.event.repository.fork == false    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install requests
      - name: Execute Python script 
        run: python sync.py ./src/catalog.json ./publish
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
      